### ISSUE TITLE
This code is not working

### ISSUE THREAD

**Issue by techpranav** [alloc7260/NSE#1]
Empty Data fram.

`C:\ProgramData\Anaconda3\envs\NSE-39\python.exe "D:\OneDrive - Technia AB\Learn\DSGS\Development\Python\NSE\Scrapper\NSE-Stock-History.py" 
Empty DataFrame
Columns: []
Index: []
Traceback (most recent call last):
  File "D:\OneDrive - Technia AB\Learn\DSGS\Development\Python\NSE\Scrapper\NSE-Stock-History.py", line 134, in <module>
    df = scrape_data('01-01-2000', '02-02-2023', 'ITC')
  File "D:\OneDrive - Technia AB\Learn\DSGS\Development\Python\NSE\Scrapper\NSE-Stock-History.py", line 112, in scrape_data
    return format_dataframe_result(result)
  File "D:\OneDrive - Technia AB\Learn\DSGS\Development\Python\NSE\Scrapper\NSE-Stock-History.py", line 121, in format_dataframe_result
    result = result[columns_required]
  File "C:\ProgramData\Anaconda3\envs\NSE-39\lib\site-packages\pandas\core\frame.py", line 3766, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "C:\ProgramData\Anaconda3\envs\NSE-39\lib\site-packages\pandas\core\indexes\base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\ProgramData\Anaconda3\envs\NSE-39\lib\site-packages\pandas\core\indexes\base.py", line 5935, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['CH_TIMESTAMP', 'CH_SYMBOL', 'CH_SERIES', 'CH_TRADE_HIGH_PRICE',\n       'CH_TRADE_LOW_PRICE', 'CH_OPENING_PRICE', 'CH_CLOSING_PRICE',\n       'CH_LAST_TRADED_PRICE', 'CH_PREVIOUS_CLS_PRICE', 'CH_TOT_TRADED_QTY',\n       'CH_TOT_TRADED_VAL', 'CH_52WEEK_HIGH_PRICE', 'CH_52WEEK_LOW_PRICE'],\n      dtype='object')] are in the [columns]"

Process finished with exit code 1
`

**Comment by alloc7260** [comment]
I have corrected mistakes so feel free to use it now. 😊
